// First-time setup for a single Windows PC (also works on macOS/Linux for testing).
//
// What it does (idempotent — safe to re-run):
//   1. Generates a strong JWT secret and writes apps/backend/.env if missing.
//   2. Writes frontend .env.local files before Next.js build.
//   3. Resolves an ABSOLUTE SQLite path (avoids Prisma's relative-path footgun
//      where the CLI resolves file: relative to the schema dir but the runtime
//      client resolves it relative to cwd).
//   4. Applies database migrations (prisma migrate deploy).
//   5. Seeds the database (system ledger accounts, owner/staff users, menu, tables).
//
// Run from the repo root:  node scripts/win-setup.mjs
// To only write env files before build: node scripts/win-setup.mjs --prepare-env
// Prereqs: `pnpm install` and `pnpm build` (or `pnpm db:generate`) already done.

import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const backendDir = join(repoRoot, "apps", "backend");
const posDir = join(repoRoot, "apps", "pos");
const adminDir = join(repoRoot, "apps", "admin");
const dataDir = join(backendDir, "data");
const dbFile = join(dataDir, "cafe.db");
const envFile = join(backendDir, ".env");
const prepareEnvOnly = process.argv.includes("--prepare-env");

// Prisma accepts forward slashes on Windows. Absolute path => the migrate CLI
// and the runtime client agree on the same database file.
const databaseUrl = `file:${dbFile.replace(/\\/g, "/")}`;

function log(message) {
  process.stdout.write(`[setup] ${message}\n`);
}

function ensureDataDir() {
  if (!existsSync(dataDir)) {
    mkdirSync(dataDir, { recursive: true });
    log(`created data directory: ${dataDir}`);
  }
}

function ensureBackendEnv() {
  let existingSecret;
  if (existsSync(envFile)) {
    // Keep the existing secret so re-running setup never invalidates sessions.
    const current = readFileSync(envFile, "utf8");
    existingSecret = current.match(/^JWT_SECRET=(.+)$/m)?.[1];
  }

  const secret = existingSecret ?? randomBytes(48).toString("base64url");
  const contents = [
    "# Auto-generated by scripts/win-setup.mjs - do NOT commit this file.",
    "NODE_ENV=production",
    `DATABASE_URL="${databaseUrl}"`,
    `JWT_SECRET="${secret}"`,
    "",
  ].join("\n");
  writeFileSync(envFile, contents, "utf8");
  if (existingSecret) {
    log("updated apps/backend/.env while preserving the existing JWT secret");
  } else {
    log("wrote apps/backend/.env with a freshly generated JWT secret");
  }
}

function ensureTextFile(file, requiredLines, label) {
  if (existsSync(file)) {
    const current = readFileSync(file, "utf8");
    const missingLines = requiredLines.filter((line) => !current.includes(line));
    if (missingLines.length === 0) {
      log(`${label} already configured — leaving it untouched`);
      return;
    }
    writeFileSync(file, `${current.trimEnd()}\n${missingLines.join("\n")}\n`, "utf8");
    log(`updated ${label}`);
    return;
  }

  writeFileSync(file, `${requiredLines.join("\n")}\n`, "utf8");
  log(`wrote ${label}`);
}

function ensureFrontendEnv() {
  ensureTextFile(
    join(posDir, ".env.local"),
    ["NEXT_PUBLIC_API_URL=http://localhost:3000"],
    "apps/pos/.env.local",
  );
  ensureTextFile(
    join(adminDir, ".env.local"),
    ["NEXT_PUBLIC_API_BASE_URL=http://localhost:3000"],
    "apps/admin/.env.local",
  );
}

function run(command, args, label) {
  log(`${label} ...`);
  const result = spawnSync(command, args, {
    cwd: backendDir,
    stdio: "inherit",
    shell: process.platform === "win32",
    env: { ...process.env, NODE_ENV: "production", DATABASE_URL: databaseUrl },
  });
  if (result.status !== 0) {
    process.stderr.write(`[setup] FAILED: ${label}\n`);
    process.exit(result.status ?? 1);
  }
}

function runPnpm(args, label) {
  run("corepack", ["pnpm", ...args], label);
}

ensureDataDir();
ensureBackendEnv();
ensureFrontendEnv();
if (prepareEnvOnly) {
  log("env files are ready for build");
  process.exit(0);
}
// pnpm exec runs the locally-installed prisma CLI; works from the backend dir.
runPnpm(["exec", "prisma", "migrate", "deploy"], "applying database migrations");
run("node", ["dist/seed/seed.service.js"], "seeding database");

log("done. Default login: owner@cafe.local / Owner123!  (change it after first login)");
